module.exports = {
	"arrowParens": "avoid",
	"bracketSameLine:": false,
	"bracketSpacing": true,
	"embeddedLanguageFormatting": "auto",
	"htmlWhitespaceSensitivity": "css",
	"insertPragma": false,
	"jsxBracketSameLine": false,
	"jsxSingleQuote": false,
	"printWidth": 80,
	"proseWrap": "preserve",
	"quoteProps": "as-needed",
	"requirePragma": false,
	"semi": true,
	"singleAttributePerLine": true,
	"singleQuote": false,
	"tabWidth": 4,
	"trailingComma": "none",
	"useTabs": false,
	"vueIndentScriptAndStyle": false
}